# Generated by Django 4.2.6 on 2023-10-25 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('matricule', models.CharField(max_length=50)),
                ('github', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=50, unique=True)),
                ('project_1', models.URLField(blank=True, null=True)),
                ('project_2', models.URLField(blank=True, null=True)),
                ('project_3', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('applicants', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='landing_page.applications')),
            ],
        ),
        migrations.AddField(
            model_name='applications',
            name='projects',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='landing_page.links'),
        ),
    ]
